#!/bin/bash

### BEGIN INIT INFO
# Provides:          farmos_gcg
# Required-Start:    mysql
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable farmos gcg service provided by daemon.
### END INIT INFO

WORK_DIR="/usr/local/farmos/bin"

case "$1" in
  start)
    echo "Starting server"
    cd "$WORK_DIR"
    ./gcg -s ../conf/farmos-server.ini -d -i 1 >> /dev/null 2>&1
    ;;
  stop)
    echo "Stopping server"
    cd "$WORK_DIR"
    ps -ef | grep './gcg -c' | grep -v grep | awk '{print $2}' | xargs kill > /dev/null
    ;;
  *)
    echo "Usage: /etc/init.d/farmos_gcg {start|stop}"
    exit 1
    ;;
esac
exit 0
